twig:
  default_path: "%kernel.project_dir%/templates"
  #   https://github.com/symfony/symfony/tree/6.1/src/Symfony/Bridge/Twig/Resources/views/Form
  form_themes: ["form.html.twig"]

when@test:
  twig:
    strict_variables: true
